@startuml
'https://plantuml.com/sequence-diagram

actor Bruger
participant "System" as System
database "Database" as Db

Bruger -> System: Login
activate System
System -> Db: Godkend Bruger
activate Db
Db -> System: Bruger godkendt
deactivate Db
System -> Bruger: Vis start side
deactivate System

Bruger -> System: Vis ønskelister
activate System
System -> Db: Hent ønskelister
activate Db
Db -> System: Send ønskelister tilbage
deactivate Db
System -> Bruger: Fremvis ønskelister
deactivate System

Bruger -> System: Tilføj ønske til liste
activate System
System -> Db: Tilføj ønske
activate Db
Db -> System: Ønske tilføjet
deactivate Db
System -> Bruger: Bekræft tilføjelse
deactivate System

@enduml
