@startuml
'https://plantuml.com/sequence-diagram

autonumber

header System sekvens diagram
actor Bruger

alt Opret bruger
    Bruger -> System: Oprette bruger
    Bruger -> System: Skriv mail og password
    Bruger <-- System: Bruger oprettet
    end

Bruger <-- System: Login page
Bruger -> System: Skriver mail og password
Bruger -> System: Bruger trykker login
Bruger <-- System: Viser forsiden

Bruger -> System: Gaveindkøb
Bruger <-- System: Vis ønskeliste(r)


alt Tilføj ønskeliste
    Bruger -> System: Opret ønskeliste
    Bruger -> System: Giv ønskelisten et navn
    Bruger <-- System: Ønskeliste oprettet
    end

alt Fjern ønskeliste
    Bruger -> System: Fjern ønskeliste
    Bruger <-- System: Fjerner ønskeliste
    end



Bruger -> System: Vælg ønskeliste
Bruger <-- System: Viser valgte ønskeliste




alt Tilføj ønske
        Bruger -> System: Tilføj ønske
            Bruger -> System: Giv ønsket et navn
        Bruger <-- System: Ønske tilføjet
        end


alt Fjern ønske
    Bruger -> System: Fjern ønske
    Bruger <-- System: Ønske fjernet
    end

alt Rediger ønske
    Bruger -> System: Rediger valgte ønske
    Bruger <-- System: Ændrer ønsket
end



@enduml