@startuml
left to right direction
actor "User" as user

usecase (Tilføj et ønske) as UC1
usecase (Vis ønsker) as UC2
usecase (Rediger dit ønske) as UC3
usecase (Slet et ønske) as UC4

user --> UC1 : Tilføjer et ønske
user --> UC2 : Viser ønsker
user --> UC3 : Redigerer et ønske
user --> UC4 : Sletter et ønske

note right of UC1
  Vælg ønkeliste / lav en ny liste
  Indtast ønske
end note

note right of UC2
  Vis liste af brugerens ønsker
end note

note right of UC3
  Vælg et ønske
  Rediger detaljer
end note

note right of UC4
  Vælg et ønske
  Vælg "Delete"
end note

@enduml
