@startuml
'https://plantuml.com/sequence-diagram

autonumber

header System sekvens diagram
actor Bruger

Bruger -> System: Login
Bruger <-- System: Viser forsiden

Bruger -> System: Gaveindkøb
Bruger <-- System: Vis ønskeliste(r)


alt Tilføj ønskeliste
    Bruger -> System: Opret ønskeliste
    Bruger -> System: Giv ønskelisten et navn
    Bruger <-- System: Ønskeliste oprettet
    end

alt Fjern ønskeliste
    Bruger -> System: Fjern ønskeliste
    Bruger <-- System: Fjerner ønskeliste
    end

Bruger -> System: Vælg ønskeliste
Bruger <-- System: Viser valgte ønskeliste

alt Tilføj ønske
    loop Ønsker tilføj
        Bruger -> System: Tilføj ønske
        Bruger <-- System: Ønske tilføjet
        end
    end

alt Fjern ønske
    Bruger -> System: Fjern ønske
    Bruger <-- System: Ønske fjernet
    end

alt Rediger ønske
    Bruger -> System: Rediger valgte ønske
    Bruger <-- System: Ændre ønsket

alt Søg Ønske
    Bruger -> System: Søg på ønske
    Bruger <-- System: Viser det søgte ønske
    end

alt Ønske købt
    loop
        Bruger -> System: Trykker på boks ved købt ønske
        Bruger <-- System: Flueben i boks ved købt ønske
        end
    end

@enduml